server:  port: 8060
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Saroop/SpringCloud
          skipSslValidation: true
          search-paths:          - config-repo/configuration/{application}
          - config-repo/configuration/          # eureka server urieureka:  client:    serviceUrl:      defaultZone: http://127.0.0.1:8050/eureka/